# See here for image details: https://github.com/microsoft/vscode-dev-containers/tree/main/containers/debian

# [Choice] Ubuntu version (use ubuntu-22.04 or ubuntu-18.04 on local arm64/Apple Silicon): 
# jammy/ubuntu-22.04, focal/ubuntu-20.04, bionic/ubuntu-18.04, debian/latest, bullseye/debian-11, buster/debian-10
# https://mcr.microsoft.com/v2/vscode/devcontainers/base/tags/list
ARG VARIANT="jammy"
FROM mcr.microsoft.com/vscode/devcontainers/base:${VARIANT}