name: Auto Bump and generate PR
on:
  workflow_dispatch

permissions: {}
jobs:
  release-PR:
    uses: murn0/generate-release-workflow/.github/workflows/release-pull-request.yaml@3d4ed1b8620894318b7d43689cd3aeb2e999e8cb # v0.7.0
    permissions:
      issues: write # For create milestone
      pull-requests: write # For pull requests to milestone
    with:
      changelog_config_json: |
        {
          "categories": [
            {
                "title": "## ⚠️ Breaking changes",
                "labels": ["breaking change"]
            },
            {
                "title": "## Features",
                "labels": [
                  "feature",
                  "enhancement"
                ]
            },
            {
                "title": "## Fixes",
                "labels": ["fix"]
            },
            {
                "title": "## Tests",
                "labels": ["test"]
            },
            {
                "title": "## Others",
                "labels": []
            },
            {
                "title": "## Dependencies",
                "labels": ["dependencies"]
            }
          ],
          "template": "#{{CHANGELOG}}"
        }
      major_title: '## ⚠️ Breaking Changes'
      minor_title: '## Features'
      labels: 'release'
      app_id_url: "op://Github/uhto3hzapjcxicwm664wvh4zu4/AppID"
      app_secret_url: "op://Github/uhto3hzapjcxicwm664wvh4zu4/private_key"
    secrets:
      op_service_account_token: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}