name: Pull request auto add label workflow
on: 
  workflow_call:
    inputs:
      app_id:
        required: true
        type: string
        description: The Secret Reference URL for the AppID stored in 1Password
      app_secret:
        required: true
        type: string
        description: The Secret Reference URL for the AppSecret stored in 1Password
    secrets:
      op_service_account_token:
        required: true

permissions: {}
jobs:
  auto-add-label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: >-
      github.event.pull_request.user.login != 'renovate[bot]' &&
      contains(github.head_ref, 'feat') ||
      contains(github.head_ref, 'fix') ||
      contains(github.head_ref, 'test') ||
      contains(github.head_ref, 'doc')
    steps:
      - name: Load secrets
        uses: 1password/load-secrets-action@d1a4e73495bde3551cf63f6c048588b8f734e21d # v1.3.1
        id: op-load-secret
        with:
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.op_service_account_token }}
          APP_ID: ${{ inputs.app_id }}
          APP_SECRET: ${{ inputs.app_secret }}

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@0d49dd721133f900ebd5e0dff2810704e8defbc6 # v1.8.2
        with:
          app_id: ${{steps.op-load-secret.outputs.APP_ID}}
          private_key: ${{steps.op-load-secret.outputs.APP_SECRET}}
      - run: |
          if [[ "$HEAD_REF" == *"feat"* ]]; then
            echo "HEADブランチに 'feat' が含まれています。"
            gh -R "$GITHUB_REPOSITORY" pr edit "$PR_NUMBER" --add-label "feature"
          elif [[ "$HEAD_REF" == *"fix"* ]]; then
            echo "HEADブランチに 'fix' が含まれています。"
            gh -R "$GITHUB_REPOSITORY" pr edit "$PR_NUMBER" --add-label "fix"
          elif [[ "$HEAD_REF" == *"test"* ]]; then
            echo "HEADブランチに 'test' が含まれています。"
            gh -R "$GITHUB_REPOSITORY" pr edit "$PR_NUMBER" --add-label "test"
          elif [[ "$HEAD_REF" == *"doc"* ]]; then
            echo "HEADブランチに 'doc' が含まれています。"
            gh -R "$GITHUB_REPOSITORY" pr edit "$PR_NUMBER" --add-label "documentation"
          fi
        env:
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}}
          PR_NUMBER: ${{github.event.pull_request.number}}
          HEAD_REF: ${{github.head_ref}}