---
name: enable-auto-merge
on:
  workflow_call:
    inputs:
      app_id:
        required: true
        type: string
        description: The Secret Reference URL for the AppID stored in 1Password
      app_secret:
        required: true
        type: string
        description: The Secret Reference URL for the AppSecret stored in 1Password
    secrets:
      op_service_account_token:
        required: true

permissions: {}
jobs:
  enable-auto-merge:
    # Enable automerge to merge pull requests from Renovate automatically.
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Load secrets
        uses: 1password/load-secrets-action@971116bbffed9bfe57bd55447317d56fbc7a6a81 # v1.3.2
        id: op-load-secret
        with:
          export-env: false
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          APP_ID: ${{ inputs.app_id }}
          APP_SECRET: ${{ inputs.app_secret }}

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        with:
          app_id: ${{steps.op-load-secret.outputs.APP_ID}}
          private_key: ${{steps.op-load-secret.outputs.APP_SECRET}}

      - run: gh -R "$GITHUB_REPOSITORY" pr merge --squash --auto --delete-branch "$PR_NUMBER"
        env:
          GITHUB_TOKEN: ${{steps.generate_token.outputs.token}} # Use GitHub App to trigger GitHub Actions Workflow by merge commit.
          PR_NUMBER: ${{github.event.pull_request.number}}