---
name: ghalint
on: workflow_call
env:
  AQUA_LOG_COLOR: always
jobs:
  ghalint:
    # Validate GitHub Actions Workflows by ghalint.
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: aquaproj/aqua-installer@96a9bc20066c5bf5e275b41019cfc165b25f4e2e # v4.0.5
        with:
          aqua_version: v2.51.2
        env:
          AQUA_GITHUB_TOKEN: ${{github.token}}
      - run: ghalint run
        env:
          GHALINT_LOG_COLOR: always
          AQUA_GITHUB_TOKEN: ${{github.token}}