---
name: test
on: workflow_call
jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu:20.04
          - ubuntu:22.04
          - debian:stretch  # Debian 9
          - debian:buster   # Debian 10
          - debian:bullseye # Debian 11
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.os }}
    permissions: {}
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: setup dotfiles
        run: |
          pwd
          whoami