---
name: test
on: workflow_call
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04, macos-12, macos-13]
    runs-on: ${{ matrix.os }}
    permissions: {}
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: setup dotfiles
        run: |
          make setup